name: Build and test

on:
  pull_request:
    branches:
      - main

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1

  build-and-test:
    needs: pre-commit

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --group test --no-dev --no-cache
      - name: Run tests
        run: uv run -- pytest

      - name: Set up minimum environment
        shell: bash
        run: |
          if [ "${{ matrix.python-version }}" == "3.13" ]; then
            GROUP="test_py13"
          else
            GROUP="test"
          fi
          uv lock --resolution lowest-direct
          uv sync --frozen --resolution lowest-direct --group "$GROUP" --no-dev --no-cache
      - name: Run tests for minimum environment
        run: |
          uv run --frozen --resolution lowest-direct -- pytest
          uv pip list
